server:
  port: ${APP_PORT:8595}

spring:
  application:
    name: kalita
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    name: ${SPRING_DATABASE_NAME:postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:50}
  jpa:
    properties:
      hibernate:
        default_schema: kalita_db
        show_sql: true
        format_sql: true

